### ISSUE TITLE
Docs: Snapshot - What’s New in Hazelcast Platform

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hz-docs#1160]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/ROOT/pages/whats-new.adoc)

v5.5 snapshot version of the doc includes what's new content for 5.4. It might confuse people. 

_PS: Today, someone told me that CP Map will be shipped with v5.5. Maybe, this was the reason 🙃  _

**Comment by Rob-Hazelcast** [comment]
Now 5.5 is the current version there's no 5.4 content in it. The V6.0 snapshot does include 5.5 content however. This is inevitable, because the next version starts life as the current version. We have recently discussed doing some admin around branch creation, which would include wiping the What's New guide. Or perhaps we could refrain from publishing the snapshot version at all.

With @oliverhowell and team to consider, but I'll close this bug for now.
