### ISSUE TITLE
Docs: Feedback for Start a Local Cluster with the CLI

### ISSUE THREAD

**Issue by esandoval30** [hazelcast/hz-docs#774]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/getting-started/pages/get-started-cli.adoc)

Running this
brew install hazelcast-management-center@5.3.1

results in 
Warning: No available formula with the name "hazelcast-management-center@5.3.1"
Did you mean hazelcast-management-center@5.3.0, hazelcast-management-center@5.2.1, hazelcast-management-center-5.3, hazelcast-management-center-5.1, hazelcast-management-center@5.1.4, hazelcast-management-center@5.1.1, hazelcast-management-center@5.0.4, hazelcast-management-center@5.2.0, hazelcast-management-center, hazelcast-management-center-5.2, hazelcast-management-center-5.0 or hazelcast-management-center@5.3.snapshot?

**Comment by Serdaro** [comment]
@esandoval30 , I don't think 5.3.1 for Management Center has been released, at least I cannot see it on its repo.
The latest supported MC for Platform's snapshot is 5.3.1-Snapshot. So the command should be `brew install hazelcast-management-center@5.3.1.SNAPSHOT`.
Should have been fixed with https://github.com/hazelcast/management-center-docs/pull/263

**Comment by amandalindsay** [comment]
Likely fixed, closing issue
