### ISSUE TITLE
Docs: Feedback for Installing Hazelcast Open Source

### ISSUE THREAD

**Issue by hjohn** [hazelcast/hz-docs#781]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/getting-started/pages/install-hazelcast.adoc)

The page mentions the following in regards to using Hazelcast with modular Java:

>The JPMS comes with stricter visibility rules. It affects Hazelcast which uses the internal Java API to reach the best performance results.

Now, in order to make the correct trade-off (allowing Hazelcast to access JDK internals VS best performance) it would be nice if this page mentions what exactly Hazelcast needs this internal access for, and what performance improvements this results in.

As it is, I couldn't find anything on this topic, so I have no idea if Hazelcast is currently crippled without opening these packages, or if it merely performs a few percent worse in some situations.  Can anyone shed some light as to the performance with and without access?

**Comment by kwart** [comment]
I'm sorry, John, we don't have such a feature list.

I remember from my Java 9 work there are some OS metrics not available. And also Hot Restart Enterprise feature depends on it (due to cleaning allocated memory).
There were also some changes related to Java 17. For the open-source part, you can check [`JDK17`-labeled pull requests](https://github.com/hazelcast/hazelcast/pulls?q=is%3Apr+label%3AJDK17)
