### ISSUE TITLE
Docs: Feedback for Start a Local Embedded Cluster

### ISSUE THREAD

**Issue by guenthermahr** [hazelcast/hz-docs#871]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/getting-started/pages/get-started-java.adoc): in order to make the SQL example work, I had to add 
<dependency>
      <groupId>com.hazelcast</groupId>
      <artifactId>hazelcast-sql</artifactId>
      <version>5.3.2</version>
    </dependency>
to the pom

**Comment by Serdaro** [comment]
Thanks @guenthermahr , let's update the relevant content accordingly.

**Comment by Serdaro** [comment]
@guenthermahr , actually the SQL tab of https://docs.hazelcast.com/hazelcast/5.3/getting-started/get-started-java#step-3-write-data-to-memory mentions what you must add to the pom.

**Comment by amandalindsay** [comment]
Can someone in Eng please confirm that to fix this, a change requires to be made on line 84 to update the </artifactId> to be hazelcast-sql so that the POM works (i.e. same as in the SQL tab on this page: https://docs.hazelcast.com/hazelcast/5.3/getting-started/get-started-java#step-3-write-data-to-memory, as mentioned in above comment). 
Thanks!

**Comment by amandalindsay** [comment]
Looking at the latest version, it appears this has been fixed as the SQL tab includes com.hazelcast, hazelcast-sql, and a version number.
